version: '3.8'

services:
  app:
      build:
        context: ./app
      ports:
        - "8080:8080"
      restart: "unless-stopped"
  www:
      build:
        context: ./app
      restart: "unless-stopped"