# version: '3.8'

configs:
  caddyfile:
    file: "${PWD}/Caddyfile"

services:
  server:
    image: caddy:2.8.4-alpine
    configs:
      - source: caddyfile
        target: "/etc/caddy/Caddyfile"
    ports:
      - "0.0.0.0:4343:443"
    restart: "unless-stopped"
  backend:
    build:
      context: ./backend
    restart: "unless-stopped"
